export default {
  fb: 'indigo',
  instagram: 'purple lighten-1',
  youtube: 'red darken-1',
  vk: 'blue darken-2',
  website: 'teal',
  pinterest: 'pink darken-4',
  twitter: 'light-blue lighten-2',
  tumblr:'blue-grey darken-3',
  linkedin:'light-blue darken-3',
  reddit:'red darken-1',
  links: 'grey',
  phone: 'green',
  skype: 'light-blue',
  messenger: 'blue darken-3',
  telegram: 'blue lighten-1',
  viber: 'deep-purple',
  whatsapp: 'light-green darken-1',
  email: 'red lighten-1',
  sms: 'green'
}
